services:
  setup:
    profiles:
      - setup
    build:
      context: setup/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    init: true
    volumes:
      - ./setup/entrypoint.sh:/entrypoint.sh:ro,Z
      - ./setup/lib.sh:/lib.sh:ro,Z
      - ./setup/roles:/roles:ro,Z
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
      METRICBEAT_INTERNAL_PASSWORD: ${METRICBEAT_INTERNAL_PASSWORD:-}
      FILEBEAT_INTERNAL_PASSWORD: ${FILEBEAT_INTERNAL_PASSWORD:-}
      HEARTBEAT_INTERNAL_PASSWORD: ${HEARTBEAT_INTERNAL_PASSWORD:-}
      MONITORING_INTERNAL_PASSWORD: ${MONITORING_INTERNAL_PASSWORD:-}
      BEATS_SYSTEM_PASSWORD: ${BEATS_SYSTEM_PASSWORD:-}
    networks:
      - elk
    depends_on:
      - elasticsearch

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - elasticsearch:/usr/share/elasticsearch/data:Z
  
      - ~/elastic-certs/node:/usr/share/elasticsearch/config/node:ro # Mount node directory
      - ~/elastic-certs/ca:/usr/share/elasticsearch/config/ca:ro     # Mount CA directory
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      xpack.security.http.ssl.certificate: /usr/share/elasticsearch/config/node/instance/instance.crt
      xpack.security.http.ssl.key: /usr/share/elasticsearch/config/node/instance/instance.key
      xpack.security.http.ssl.key_passphrase: phuongk16cntt2
      xpack.security.http.ssl.certificate_authorities: /usr/share/elasticsearch/config/ca/ca.crt
      discovery.type: single-node
    networks:
      - elk
    restart: unless-stopped

  logstash:
    build:
      context: logstash/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    ports:
      - 5044:5044
      - 50000:50000/tcp
      - 50000:50000/udp
      - 9600:9600
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: unless-stopped

  kibana:
    build:
      context: kibana/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
      - ~/elastic-certs/node:/usr/share/kibana/config/node:ro # Mount node directory
      - ~/elastic-certs/ca:/usr/share/kibana/config/ca:ro   # Mount CA directory
    ports:
      - 5601:5601
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
      xpack.security.encryptionKey: ${KIBANA_ENCRYPTION_KEY:-}
      SERVER_SSL_ENABLED: "true"
      SERVER_SSL_CERTIFICATE: /usr/share/kibana/config/node/instance/instance.crt
      SERVER_SSL_KEY: /usr/share/kibana/config/node/instance/instance.key
      SERVER_SSL_KEY_PASSPHRASE: phuongk16cntt2
      SERVER_SSL_CERTIFICATE_AUTHORITIES: /usr/share/kibana/config/ca/ca.crt
      ELASTICSEARCH_SSL_CERTIFICATE_AUTHORITIES: /usr/share/kibana/config/ca/ca.crt
      ELASTICSEARCH_SSL_VERIFICATION_MODE: certificate
      XPACK_FLEET_FLEET_SERVER_HOST: https://172.17.0.1:8220
    networks:
      - elk
    dns:
      - 8.8.8.8
      - 1.1.1.1
    depends_on:
      - elasticsearch
    restart: unless-stopped

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch:
