---
## Default Logstash configuration from Logstash base image.
## https://github.com/elastic/logstash/blob/main/docker/data/logstash/config/logstash-full.yml
#
api.http.host: 0.0.0.0

queue.type: persisted
queue.max_bytes: 10gb
queue.checkpoint.writes: 1024
queue.checkpoint.interval: 1000



node.name: logstash
